server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/motor-depot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG